# Generated by Django 3.2.8 on 2021-10-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('first_surname', models.CharField(max_length=255)),
                ('second_surname', models.CharField(max_length=255)),
                ('identity_number', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('cellphone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('admin_status', models.CharField(max_length=255)),
                ('activity_status', models.CharField(max_length=255)),
                ('id_rol', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
