# Generated by Django 3.2.8 on 2021-11-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reuniones_copasst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta', models.CharField(max_length=255)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='archivos_copasst',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plan_copasst',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
