# Generated by Django 3.2.8 on 2021-11-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='riesgos_emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgosFile', models.FileField(upload_to='media/')),
                ('emergenciaFile', models.FileField(upload_to='media/')),
            ],
        ),
    ]
