# Generated by Django 3.2.8 on 2021-11-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0002_auto_20211128_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos_copasst',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plan_copasst',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reuniones_copasst',
            name='fecha',
            field=models.DateField(),
        ),
    ]
