# Generated by Django 3.2.8 on 2021-10-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0002_permissions_permissions_role_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions_role',
            name='id_permission',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='permissions_role',
            name='id_rol',
            field=models.IntegerField(),
        ),
    ]
