# Generated by Django 3.2.8 on 2021-11-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0002_copasst'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_copasst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
