# Generated by Django 3.2.8 on 2021-11-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0002_riesgos_emergencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riesgos_emergencia',
            name='emergenciaFile',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='riesgos_emergencia',
            name='riesgosFile',
            field=models.CharField(max_length=255),
        ),
    ]
