# Generated by Django 3.2.8 on 2021-11-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0002_producto_aliado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_aliado',
            old_name='id_aliado',
            new_name='aliado',
        ),
    ]
