# Generated by Django 3.2.8 on 2021-11-25 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0002_cocola_copasst_plan_copasst_quejas_cocola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_copasst',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 11, 25, 11, 14, 16, 9984, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quejas_cocola',
            name='fechaInscripcion',
            field=models.DateField(auto_now=True),
        ),
    ]
