# Generated by Django 3.2.8 on 2021-11-23 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0003_plan_copasst'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_copasst',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 11, 23, 12, 4, 45, 109378, tzinfo=utc)),
        ),
    ]
