# Generated by Django 3.2.8 on 2021-10-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0003_auto_20211021_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='rol_name',
            new_name='name',
        ),
    ]
