# Generated by Django 3.2.8 on 2021-11-25 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0003_auto_20211125_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_copasst',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 11, 25, 11, 21, 40, 766464, tzinfo=utc)),
        ),
    ]
