# Generated by Django 3.2.8 on 2021-11-25 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0004_alter_plan_copasst_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_copasst',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 11, 25, 11, 22, 38, 694800, tzinfo=utc)),
        ),
    ]
