# Generated by Django 3.2.8 on 2021-11-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0005_alter_plan_copasst_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_copasst',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
