# Generated by Django 3.2.8 on 2021-10-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0005_auto_20211026_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cellphone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='identity_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
