# Generated by Django 3.2.8 on 2021-10-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0006_auto_20211026_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=255)),
                ('georreferencia', models.CharField(max_length=255)),
                ('actividad_economica', models.CharField(max_length=255)),
                ('nivel_riesgo', models.CharField(max_length=255)),
                ('cant_trabajadores', models.CharField(max_length=255)),
                ('naturaleza_juridica', models.CharField(max_length=255)),
                ('telefono_contacto', models.CharField(max_length=255)),
                ('email_contacto', models.CharField(max_length=255)),
                ('tipo_empresa', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
