# Generated by Django 2.1.15 on 2021-10-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sst', '0007_auto_20211027_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20)),
                ('compromisos', models.TextField()),
                ('requisitos_legales', models.TextField()),
                ('objetivos', models.TextField()),
                ('comentarios', models.TextField()),
                ('firma', models.CharField(max_length=30)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Politica',
                'verbose_name_plural': 'Politicas',
            },
        ),
    ]
